logging:
  level:
    root: info
#    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: trace
#    org.jooq.tools.LoggerListener: debug
#    win.doyto.query.sql.SqlAndArgs: debug

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.1.123:5432/povice
    username: test
    password: test1004
  sql:
    init:
      mode: never
      schema-locations: classpath:schema-postgresql.sql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    open-in-view: off

doyto:
  query:
    config:
      table-format: "%s"
